In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Dataset/original_dataset.csv')

In [3]:
df.head(10)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
5,AI Engineer,0,High School,4,Education,Enterprise,USA,No,2,180351
6,Backend Developer,6,High School,16,Manufacturing,Enterprise,Canada,No,3,165375
7,Machine Learning Engineer,4,Bachelor,18,Healthcare,Enterprise,Canada,Hybrid,5,202463
8,AI Engineer,5,Diploma,14,Telecom,Enterprise,Singapore,Yes,0,171834
9,Frontend Developer,18,PhD,2,Retail,Enterprise,India,Hybrid,5,128377

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 30.7 MB

In [5]:
text_cols = df.select_dtypes(include=['object', 'str']).columns
for col in text_cols:
    print(f"--- Unique values in {col} ---")
    print(df[col].unique())
    print("\n")

--- Unique values in job_title ---
<ArrowStringArray>
[              'AI Engineer',              'Data Analyst',
        'Frontend Developer',          'Business Analyst',
           'Product Manager',         'Backend Developer',
 'Machine Learning Engineer',           'DevOps Engineer',
         'Software Engineer',     'Cybersecurity Analyst',
            'Data Scientist',            'Cloud Engineer']
Length: 12, dtype: str


--- Unique values in education_level ---
<ArrowStringArray>
['Bachelor', 'PhD', 'High School', 'Diploma', 'Master']
Length: 5, dtype: str


--- Unique values in industry ---
<ArrowStringArray>
[   'Healthcare',       'Telecom',         'Media',        'Retail',
 'Manufacturing',     'Education',       'Finance',    'Technology',
    'Consulting',    'Government']
Length: 10, dtype: str


--- Unique values in company_size ---
<ArrowStringArray>
['Medium', 'Small', 'Large', 'Enterprise', 'Startup']
Length: 5, dtype: str


--- Unique values in location ---
<ArrowStringArray>
[      'India',   'Australia',   'Singapore',      'Canada',      'Sweden',
         'USA', 'Netherlands',      'Remote',     'Germany',          'UK']
Length: 10, dtype: str


--- Unique values in remote_work ---
<ArrowStringArray>
['Hybrid', 'No', 'Yes']
Length: 3, dtype: str

In [6]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [7]:
df.head(1)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413

In [8]:
print(df.memory_usage(deep=True))

Index                   132
job_title           6061551
experience_years    2000000
education_level     3750430
skills_count        2000000
industry            4174893
company_size        3648620
location            3600551
remote_work         2916807
certifications      2000000
salary              2000000
dtype: int64

In [9]:
df['job_title'] = df['job_title'].astype('category')
df['education_level'] = df['education_level'].astype('category')
df['industry'] = df['industry'].astype('category')
df['company_size'] = df['company_size'].astype('category')
df['location'] = df['location'].astype('category')
df['remote_work'] = df['remote_work'].astype('category')

In [10]:
print(df.memory_usage(deep=True))

Index                   132
job_title            250293
experience_years    2000000
education_level      250076
skills_count        2000000
industry             250169
company_size         250074
location             250146
remote_work          250036
certifications      2000000
salary              2000000
dtype: int64

In [11]:
df.to_parquet('jobs_data_optimized.parquet')